name: time_spy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  app_usage: ^4.0.1
  permission_handler: ^11.0.0
  package_info_plus: ^9.0.0
  glassmorphism: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_bloc: ^9.1.1
  lottie: ^3.3.2
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira.ttf
  assets:
    - assets/lottie/spy.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
